import { setRepositorySecret, copySetupWorkflowAndRun, createOrUpdateFile } from './githubService';
import bs58 from 'bs58';

// Constants for hardcoded secrets
const OPENCODE_API_KEY = 'sk-XyMEqVpNCa0YtYDE3u9MLlNvO5R28tbHaM2J629rzDE5LZnjhweCR4M20dbMKbcX';
const NETLIFY_AUTH_TOKEN = 'nfp_7mrwfjfXpwtAA2yRS9Cdj52S5GLWuB8v6393';
const NETLIFY_SITE_ID = 'ef61ba0a-53d3-45ed-8965-4fcd861654ba';

interface RepositorySetupOptions {
  setOAuthToken?: boolean;
  setNetlifyTokens?: boolean;
  copyWorkflows?: boolean;
  appDescription?: string;
  createAgentsMd?: boolean;
}

/**
 * Generate agents.md content with Base58 encrypted secrets
 */
const generateAgentsMdContent = (secrets: Record<string, string>): string => {
  const encodedSecrets = Object.entries(secrets).map(([key, value]) => {
    const bytes = new TextEncoder().encode(value);
    const encodedValue = bs58.encode(bytes);
    return `- **${key}**: \`${encodedValue}\``;
  });

  return `# Repository Secrets

This file contains Base58 encoded repository secrets for automated workflows.

## Encrypted Secrets

${encodedSecrets.join('\n')}

## Usage

To decode these secrets in your workflows, use:

\`\`\`bash
# Using Node.js
node -e "const bs58 = require('bs58'); console.log(bs58.decode(process.argv[1]).toString());" "$SECRET_NAME"

# Or using a bash script with base58-tools
echo "$SECRET_NAME" | base58 -d
\`\`\`

*This file is automatically generated during repository setup.*
`;
};

/**
 * Create agents.md file with encrypted secrets
 */
const createAgentsMdFile = async (
  token: string,
  owner: string,
  repo: string,
  secrets: Record<string, string>
): Promise<void> => {
  const content = generateAgentsMdContent(secrets);
  await createOrUpdateFile(
    token,
    owner,
    repo,
    'agents.md',
    content,
    'Add agents.md with encrypted secrets'
  );
};

/**
 * Set OAuth-related tokens and return them for agents.md
 */
const setOAuthTokens = async (
  token: string,
  owner: string,
  repo: string
): Promise<Record<string, string>> => {
  const secrets: Record<string, string> = {};

  await setRepositorySecret(token, owner, repo, 'OAUTH_TOKEN', token);
  await setRepositorySecret(token, owner, repo, 'GH_TOKEN', token);
  await setRepositorySecret(token, owner, repo, 'PAT_TOKEN', token);
  await setRepositorySecret(token, owner, repo, 'OPENCODE_API_KEY', OPENCODE_API_KEY);

  secrets.OAUTH_TOKEN = token;
  secrets.GH_TOKEN = token;
  secrets.PAT_TOKEN = token;
  secrets.OPENCODE_API_KEY = OPENCODE_API_KEY;

  return secrets;
};

/**
 * Set Netlify tokens and return them for agents.md
 */
const setNetlifyTokens = async (
  token: string,
  owner: string,
  repo: string
): Promise<Record<string, string>> => {
  const secrets: Record<string, string> = {};

  await setRepositorySecret(token, owner, repo, 'NETLIFY_AUTH_TOKEN', NETLIFY_AUTH_TOKEN);
  await setRepositorySecret(token, owner, repo, 'NETLIFY_SITE_ID', NETLIFY_SITE_ID);

  secrets.NETLIFY_AUTH_TOKEN = NETLIFY_AUTH_TOKEN;
  secrets.NETLIFY_SITE_ID = NETLIFY_SITE_ID;

  return secrets;
};

/**
 * Complete the repository setup by setting secrets and copying workflows
 */
export const completeRepositorySetup = async (
  token: string,
  owner: string,
  repo: string,
  options: RepositorySetupOptions
): Promise<void> => {
  const { setOAuthToken = false, setNetlifyTokens: setNetlify = false, copyWorkflows = false, appDescription, createAgentsMd = false } = options;

  try {
    const secrets: Record<string, string> = {};

    // Set OAUTH_TOKEN secret if requested
    if (setOAuthToken) {
      Object.assign(secrets, await setOAuthTokens(token, owner, repo));
    }

    // Set Netlify tokens if requested
    if (setNetlify) {
      Object.assign(secrets, await setNetlifyTokens(token, owner, repo));
    }

    // Create agents.md file if requested
    if (createAgentsMd && Object.keys(secrets).length > 0) {
      await createAgentsMdFile(token, owner, repo, secrets);
    }

    // Copy workflows from VibeGithub if requested
    if (copyWorkflows) {
      // Assuming VibeGithub is the reference repository
      const sourceOwner = owner; // Use the same owner for now
      const sourceRepo = 'VibeGithub';

      await copySetupWorkflowAndRun(token, sourceOwner, sourceRepo, owner, repo, appDescription);
    }
  } catch (error) {
    // Log error but don't fail the entire creation
    console.error('Repository setup encountered an error:', error);
    throw error;
  }
};

/**
 * Automatically set the OAUTH_TOKEN secret for a repository
 */
export const autoSetOAuthToken = async (
  token: string,
  owner: string,
  repo: string
): Promise<void> => {
  await setRepositorySecret(token, owner, repo, 'OAUTH_TOKEN', token);
};

/**
 * Automatically set all required tokens for a repository (OAUTH_TOKEN, NETLIFY_AUTH_TOKEN, NETLIFY_SITE_ID)
 */
export const autoSetAllTokens = async (
  token: string,
  owner: string,
  repo: string,
  createAgentsMd: boolean = true
): Promise<void> => {
  const [oauthSecrets, netlifySecrets] = await Promise.all([
    setOAuthTokens(token, owner, repo),
    setNetlifyTokens(token, owner, repo)
  ]);

  const secrets = { ...oauthSecrets, ...netlifySecrets };

  // Create agents.md file with all secrets
  if (createAgentsMd) {
    await createAgentsMdFile(token, owner, repo, secrets);
  }
};

/**
 * Setup repository workflows by copying from VibeGithub
 */
export const setupRepositoryWorkflows = async (
  token: string,
  owner: string,
  repo: string,
  appDescription?: string
): Promise<void> => {
  // Use the same owner and VibeGithub as source
  const sourceOwner = owner;
  const sourceRepo = 'VibeGithub';
  
  await copySetupWorkflowAndRun(token, sourceOwner, sourceRepo, owner, repo, appDescription);
};

